apiVersion:  apps/v1
kind: Deployment
metadata:
    name: gateway
    namespace:  archref
spec:
    replicas:  2
   selector:
       matchLabels:
           app: gateway
    template:
       metadata:
          labels:
               app: gateway
       spec:
           containers:
              -  name:  gateway
                  image: <ACR_NAME>.azurecr.io/gateway:1.0.0
                  ports:
                      - containerPort:  80
                  readinessProbe:
                     httpGet:
                         path:  /healthz
                         port:  80
                     initialDelaySeconds:  5
                      periodSeconds: 10
---
apiVersion:  v1
kind: Service
metadata:
    name: gateway
    namespace:  archref
spec:
    selector:
       app:  gateway
   ports:
       -  port:  80
          targetPort:  80
   type:  ClusterIP
