apiVersion:  autoscaling/v2
kind:  HorizontalPodAutoscaler
metadata:
   name:  orders-hpa
   namespace:  archref
spec:
   scaleTargetRef:
       apiVersion:  apps/v1
       kind:  Deployment
       name:  orders
   minReplicas:  2
   maxReplicas:  10
   metrics:
       -  type:  Resource
           resource:
              name:  cpu
              target:
                  type: Utilization
                  averageUtilization:  60
