name:  PR  Quality
on:
    pull_request:
       branches:  [ "main"  ]
jobs:
   quality:
       runs-on:  ubuntu-latest
       steps:
           -  uses: actions/checkout@v4
           -  name:  Python lint
               run: |
                  pipx  install  flake8
                  cd src/services/orders
                  flake8  .
           - name:  Node  install
              run:  |
                  cd  src/services/catalog
                 npm  install  --omit=dev
